############ If Certificates exist? ##################################

- name: Check if there is a website certificate locally
  become: False
  local_action:
    module: stat
    path: "roles/apache/files/{{ fqdn }}.crt"
  register: have_web_cert

- name: Check if there is a website key locally
  become: False
  local_action:
    module: stat
    path: "roles/apache/files/{{ fqdn }}.key"
  register: have_web_key

################## Then < Copy existing certificates to remote #######################
- name: Copy TLS key
  copy: > 
    src={{ fqdn }}.key 
    dest={{ certificate_key_path }}
    owner=root
    group=ssl-cert
    mode=0600
  when: have_web_key.stat.exists == True
  notify: restart apache

- name: Copy TLS certificate
  copy: > 
    src={{ fqdn }}.crt 
    dest={{ certificate_cert_path }}
  when: have_web_cert.stat.exists == True
  notify: restart apache

############ Else > Create self-signed certificates ##################################
- name: Copy Web certificate config file
  template: >
    src=web_cert.cnf.j2
    dest=/tmp/web_cert.cnf
  when: (have_web_cert.stat.exists == False) and (have_web_key.stat.exists == False)

- name: Generate key and certificate
  command: openssl req -x509 -nodes -days 1095 -newkey rsa:2048 -config /tmp/web_cert.cnf -keyout {{ certificate_key_path }} -out {{ certificate_cert_path }}
  when: (have_web_cert.stat.exists == False) and (have_web_key.stat.exists == False)

- name: Tighten permission on key
  file: > 
    path={{ certificate_key_path }} 
    owner=root
    group=ssl-cert
    mode=0600
  when: (have_web_cert.stat.exists == False) and (have_web_key.stat.exists == False)

################## End Certificates #######################