- name: Copy index.html page
  template: >
    src=index.html.j2
    dest=/var/www/html/index.html

- name: Copy Logo
  copy: >
    src="{{ sp.logo | default('logo-default.png')}}"
    dest=/var/www/html/logo.png

- name: Copy response.html page
  copy: >
    src=response.html
    dest=/var/www/html/response.html

- name: Create secured directory
  file: >
    path=/var/www/html/secure
    state=directory

- name: Copy secure index.html page
  copy: >
    src=secure_index.html
    dest=/var/www/html/secure/index.html

- name: Copy congrats pic
  copy: >
    src=congrats-to-you.jpg
    dest=/var/www/html/secure/congrats-to-you.jpg

- name: Create secured directory
  file: >
    path=/var/www/html/students_only
    state=directory

- name: Copy secure index.html page
  copy: >
    src=students_only_index.html
    dest=/var/www/html/students_only/index.html

- name: Copy congrats2 pic
  copy: >
    src=congrats2.jpg
    dest=/var/www/html/students_only/congrats2.jpg

- name: Copy hands-on pic
  copy: >
    src=hands-on.png
    dest=/var/www/html/hands-on.png

