- name: Install example of a Shibboleth Service Provider for UbuntuNet Alliance
  hosts: sp
  become: True
  tasks:
    # I Installation
    # https://www.switch.ch/aai/guides/sp/installation/?os=ubuntu

    # 2. Prerequisites
    - name: Install needed utility programs
      apt: pkg={{ item }} update_cache=yes cache_valid_time=36000
      with_items:
        - ntp
        - unzip

    # Apache

    - name: Install apache2
      apt: pkg=apache2 update_cache=yes cache_valid_time=36000

    - name: Enable Apache SSL and Rewrite modules
      command: a2enmod ssl rewrite
      notify: restart apache

    - name: Copy apache2 config file
      template: >
        src=apache2.conf.j2
        dest=/etc/apache2/sites-available/{{ fqdn }}.conf
      notify: restart apache

    - name: Disable default configuration
      command: a2dissite 000-default
      notify: restart apache

    - name: Enable IdP configuration
      command: a2ensite {{ fqdn }}
      notify: restart apache


    - name: Add default ServerName
      template: >
        src=apache2_fqdn.conf.j2
        dest=/etc/apache2/conf-available/fqdn.conf
      notify: restart apache

    - name: Enable default ServerName
      command: a2enconf fqdn
      notify: restart apache


    ############ If Certificates exist? ##################################

    - name: Check if there is a website certificate locally
      become: False
      local_action:
        module: stat
        path: "files/{{ fqdn }}.crt"
      register: have_web_cert

    - name: Check if there is a website key locally
      become: False
      local_action:
        module: stat
        path: "files/{{ fqdn }}.key"
      register: have_web_key

    ################## Then < Copy existing certificates to remote #######################
    - name: Copy TLS key
      copy: > 
        src=files/{{ fqdn }}.key 
        dest={{ certificate_key_path }}
        owner=root
        group=ssl-cert
        mode=0600
      when: have_web_key.stat.exists == True
      notify: restart apache

    - name: Copy TLS certificate
      copy: > 
        src=files/{{ fqdn }}.crt 
        dest={{ certificate_cert_path }}
      when: have_web_cert.stat.exists == True
      notify: restart apache

    ############ Else > Create self-signed certificates ##################################
    - name: Copy Web certificate config file
      template: >
        src=web_cert.cnf.j2
        dest=/tmp/web_cert.cnf
      when: (have_web_cert.stat.exists == False) and (have_web_key.stat.exists == False)

    - name: Generate key and certificate
      command: openssl req -x509 -nodes -days 1095 -newkey rsa:2048 -config /tmp/web_cert.cnf -keyout {{ certificate_key_path }} -out {{ certificate_cert_path }}
      when: (have_web_cert.stat.exists == False) and (have_web_key.stat.exists == False)

    - name: Tighten permission on key
      file: > 
        path={{ certificate_key_path }} 
        owner=root
        group=ssl-cert
        mode=0600

    ################## End Certificates #######################



    # 3. Shibboleth Repository

    - name: Create download directory
      file: >
        path=/usr/local/dist
        state=directory

    - name: Download Switch Repository Key
      get_url: url=http://pkg.switch.ch/switchaai/SWITCHaai-swdistrib.asc dest=/usr/local/dist/

    - name: Add Repository Key
      command: apt-key add /usr/local/dist/SWITCHaai-swdistrib.asc

    - name: Copy Repository
      copy: > 
        src=files/SWITCHaai-swdistrib.list 
        dest=/etc/apt/sources.list.d/

    - name: Refresh Repository
      apt: update_cache=yes


    # 4. Installation

    - name: Install Shibboleth
      apt: pkg=shibboleth update_cache=yes cache_valid_time=36000


    # II Configuration
    # https://www.switch.ch/aai/guides/sp/configuration/

    # 4. X.509 certificate for SAML message signing/encrypting
    - name: Create self-signed certificate
      command: shib-keygen -f -u _shibd -h {{ fqdn }} -y 3 -e https://{{ fqdn }}/shibboleth -o /etc/shibboleth/


    # 5. Shibboleth Configuration
    
    - name: Copy Shibboleth config file
      template: >
        src=templates/shibboleth2.xml.j2
        dest=/etc/shibboleth/shibboleth2.xml
      notify: restart shibboleth
    
    - name: Copy IdP metadata file
      template: >
        src=templates/idp_dev-metadata.xml.j2
        dest=/etc/shibboleth/idp_dev-metadata.xml
      notify: restart shibboleth

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

    - name: restart shibboleth
      service: name=shibd state=restarted

