- name: Install example of a Shibboleth Service Provider for UbuntuNet Alliance
  hosts: sp
  become: True

  roles:
    - webserver
    - shibboleth_sp

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted

  - name: restart shibboleth
    service: name=shibd state=restarted

