- name: Install example of a Shibboleth Service Provider for UbuntuNet Alliance
  hosts: sp
  become: True

  vars_files:
    - group_vars/secrets.yml

  roles:
    - webserver
    - sp
    - newrelic

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted

  - name: restart shibboleth
    service: name=shibd state=restarted

