# II Configuration
# https://www.switch.ch/aai/guides/sp/configuration/



- name: Copy signing key
  copy: > 
    src={{ fqdn }}_sp-key 
    dest=/etc/shibboleth/sp-key.pem
  # when: have_sign_key.stat.exists == True

- name: Copy signing certificate
  copy: > 
    src={{ fqdn }}_sp-cert
    dest=/etc/shibboleth/sp-cert.pem
  # when: have_sign_cert.stat.exists == True


# 4. X.509 certificate for SAML message signing/encrypting
# - name: Create self-signed certificate
#   command: shib-keygen -f -u _shibd -h {{ fqdn }} -y 3 -e https://{{ fqdn }}/shibboleth -o /etc/shibboleth/
#   args:
#     creates: /etc/shibboleth/sp-key.pem

# - name: Copy certificate to this machine
#   fetch: >
#     src=/etc/shibboleth/sp-cert.pem 
#     dest=roles/sp/files/{{ fqdn }}_sp-cert.pem 
#     flat=yes

# 5. Shibboleth Configuration



- name: Copy Shibboleth config file
  template: >
    src=shibboleth2.xml.j2
    dest=/etc/shibboleth/shibboleth2.xml
  notify: restart shibboleth

- name: Copy attribute-map file
  template: >
    src=attribute-map.xml.j2
    dest=/etc/shibboleth/attribute-map.xml
  notify: restart shibboleth

- name: Copy attribute-policy file
  template: >
    src=attribute-policy.xml.j2
    dest=/etc/shibboleth/attribute-policy.xml
  notify: restart shibboleth


# - name: Copy IdP metadata file
#   template: >
#     src={{ metadata_file }}.j2
#     dest=/etc/shibboleth/{{ metadata_file }}
#   notify: restart shibboleth

- name: Copy Federation Metadata signer certificate
  copy: >
    src=fedsigner
    dest=/etc/shibboleth/fedsigner.pem
  notify: restart shibboleth

- name: Download Metadata Backup File from RR 
  get_url: > 
    url={{ metadata_url }}
    dest=/etc/shibboleth/{{ metadata_file }}
  notify: restart shibboleth

- name: Hand /etc/shibboleth over to the _shibd user
  file: >
    path=/etc/shibboleth
    owner=_shibd
    recurse=yes 

