- name: Install Shibboleth IdP v3 for UbuntuNet Alliance
  hosts: development
  become: True  
  vars:
    home_organisation_name: ubuntunet.net
    # fully_qualified_service_name: 192.168.33.44
    fully_qualified_service_name: idp.{{ home_organisation_name }}
    ip_address: 192.168.33.44
    entity_id: https://192.168.33.44/idp/shibboleth
    # entity_id: https://{{ fully_qualified_service_name }}/shibboleth/idp
    # entity_id: https://{{ fully_qualified_service_name }}/idp/shibboleth
    admin_email: idp@ubuntunet.net
    # idp_home: /opt/shibboleth-idp
    certificate_key_path: /etc/ssl/private/{{ fully_qualified_service_name }}.key
    certificate_cert_path: /etc/ssl/certs/{{ fully_qualified_service_name }}.crt
    tomcat_version: 7
    catalina_home: /usr/share/tomcat7
    catalina_base: /var/lib/tomcat7
    postgres_version: 9.3
    shibboleth_version: 3.2.1
    ldap_url: 192.168.33.10
    ldap_port: 389
    ldap_protocol: http

  tasks:
    # 1. Systems Requirememts
    - name: Install needed utility programs
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      with_items:
        - ntp
        - unzip

    # 3. Apache HTTP Server installation
    - name: Install apache2
      apt: pkg=apache2 update_cache=yes cache_valid_time=3600

    - name: Copy apache2 config file
      template: >
        src=templates/apache2.conf.j2
        dest=/etc/apache2/sites-available/{{ fully_qualified_service_name }}.conf
      notify: restart apache

    - name: Disable default configuration
      command: a2dissite 000-default
      notify: restart apache

    - name: Enable IdP configuration
      command: a2ensite {{ fully_qualified_service_name }}
      notify: restart apache

    - name: Copy TLS key
      copy: > 
        src=files/{{ fully_qualified_service_name }}.key 
        dest={{ certificate_key_path }}
        owner=root
        group=ssl-cert
        mode=0600
      notify: restart apache

    - name: Copy TLS certificate
      copy: > 
        src=files/{{ fully_qualified_service_name }}.crt 
        dest={{ certificate_cert_path }}
      notify: restart apache

    - name: Enable SSL and AJP Proxy modules
      command: a2enmod ssl proxy_ajp
      notify: restart apache


    # 4. Java Servlet Container Installation

    # 4.1. Java runtime environment: OpenJDK 7
    # Replace with Oracle Java 
    - name: Install OpenJDK 7
      apt: name=openjdk-7-jdk update_cache=yes cache_valid_time=3600

    # 4.2. Servlet container: Apache Tomcat 7
    - name: Install Tomcat 7
      apt: name=tomcat{{ tomcat_version }} update_cache=yes cache_valid_time=3600

    - name: Copy Tomcat config file
      copy: > 
        src=files/tomcat.xml 
        dest=/etc/tomcat{{ tomcat_version }}/server.xml
      notify: restart tomcat

    - name: Adjust JAVA options
      replace: >
        dest=/etc/default/tomcat{{ tomcat_version }} 
        regexp='JAVA_OPTS="-Djava.awt.headless=true -Xmx128m -XX:\+UseConcMarkSweepGC"' 
        replace='JAVA_OPTS="-server -Xmx1024m -Djava.security.egd=file:/dev/./urandom"'


    # 5. SQL database: PostgreSQL 9

    # 5.1. Installation
    - name: Install Postgres, Java Adapter and Psycog for postgresql_db module
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      with_items:
        - postgresql
        - libpostgresql-jdbc-java
        - python-psycopg2

    # 5.2. Database creation and settings
    - name: Create DB user
      become_user: postgres
      postgresql_user: name=shibboleth 

    - name: Create database for Shibboleth
      become_user: postgres
      postgresql_db: >
        name=shibboleth
        encoding='UTF-8'
        template='template0'
        owner=shibboleth

    - name: Copy tables script
      copy: src="files/tables.sql" dest="/tmp/tables.sql"

    - name: Create tables
      become_user: postgres
      shell:  "psql -f /tmp/tables.sql shibboleth"

    - name: Enable autovacuum
      replace: >
        dest=/etc/postgresql/{{ postgres_version }}/main/postgresql.conf 
        regexp='#autovacuum_vacuum_scale_factor = 0.2' 
        replace='autovacuum_vacuum_scale_factor = 0.002'

    - name: Enable autoanalyze
      replace: >
        dest=/etc/postgresql/{{ postgres_version }}/main/postgresql.conf 
        regexp='#autovacuum_analyze_scale_factor = 0.1' 
        replace='autovacuum_analyze_scale_factor = 0.001'
      notify: restart postgres

    # 5.3. Database backup
    - name: Create backup directory
      file: >
        path=/var/backups/postgresql 
        state=directory
        owner=postgres
        group=postgres
        mode=0700


    # 6. Shibboleth IdP

    # 6.1. IdP installation
    - name: Create download directory
      file: >
        path=/usr/local/dist
        state=directory

    - name: Download Shibboleth IdP
      get_url: > 
        url=https://shibboleth.net/downloads/identity-provider/{{ shibboleth_version }}/shibboleth-identity-provider-{{ shibboleth_version }}.tar.gz
        dest=/usr/local/dist/shibboleth-identity-provider-{{ shibboleth_version }}.tar.gz

    - name: Extract Shibboleth IdP
      unarchive: > 
        src=/usr/local/dist/shibboleth-identity-provider-{{ shibboleth_version }}.tar.gz 
        dest=/usr/local/dist
        copy=no

    - name: Copy customised install script
      template: >
        src=templates/idp-install.sh.j2
        dest=/usr/local/dist/idp-install.sh
        mode=0700


    - name: Install Shibboleth IdP
      command: ./idp-install.sh chdir=/usr/local/dist

    # 6.2. General IdP settings: services.xml and global.xml
    # - name: Adapt MetadataResolverResources in services.xml
    #   replace: >
    #     dest=/opt/shibboleth-idp/conf/services.xml 
    #     regexp='<value>%{idp.home}/conf/metadata-providers.xml</value>' 
    #     replace="<value>#{ '%{idp.metadata}' matches '.*\bswitchaai\b.*' ? '%{idp.home}/conf/metadata-provider-switchaai.xml' : '' }</value>
    #              <value>#{ '%{idp.metadata}' matches '.*\binterfederation\b.*' ? '%{idp.home}/conf/metadata-provider-interfederation.xml' : '' }</value>"

    # - name: Adapt AttributeFilterResources in services.xml
    #   replace: >
    #     dest=/opt/shibboleth-idp/conf/services.xml 
    #     regexp='<value>%{idp.home}/conf/attribute-filter.xml</value>' 
    #     replace='<ref bean="FileBackedSWITCHaaiAttributeFilter"/>'

    #TODO - Insert this part as well
    # <bean id="FileBackedSWITCHaaiAttributeFilter"
    #       class="net.shibboleth.ext.spring.resource.FileBackedHTTPResource"
    #       c:client-ref="#{ '%{idp.http.proxyhost:null}' != 'null' ?
    #                        'shibboleth.ProxyHttpClient' : 'shibboleth.HttpClient' }"
    #       c:url="https://rr.aai.switch.ch/switchaai/example.org/attribute-filter.xml"
    #       c:backingFile="%{idp.home}/conf/attribute-filter.switchaai.xml">
    # </bean>

    # - name: Create attribute-filter.xml
    #   file: >
    #     path=/opt/shibboleth-idp/conf/attribute-filter.ubuntunet.xml 
    #     state=touch
    #     owner=tomcat{{ tomcat_version }}

    - name: Copy global.xml
      copy: > 
        src=files/global.xml
        dest=/opt/shibboleth-idp/conf

    # 6.3. Federation metadata configuration
    # - name: Copy SWITCH metadata providers
    #   copy: > 
    #     src=files/metadata-provider-switchaai.xml 
    #     dest=/opt/shibboleth-idp/conf

    # - name: Copy interfederation metadata providers
    #   copy: > 
    #     src=files/metadata-provider-interfederation.xml 
    #     dest=/opt/shibboleth-idp/conf

    # - name: Copy Trust Anchor Root Certificate
    #   copy: > 
    #     src=files/SWITCHaaiRootCA.crt.pem
    #     dest=/opt/shibboleth-idp/credentials

    - name: Copy IdP properties
      template: >
        src=templates/idp.properties.j2
        dest=/opt/shibboleth-idp/conf

    # - name: Insert Metadata Reference
    #   lineinfile: >
    #     dest=/opt/shibboleth-idp/conf/idp.properties
    #     insertafter=EOF
    #     line="idp.metadata = switchaai, interfederation"

    # - name: Copy UbuntuNet metadata providers
    #   copy: > 
    #     src=files/metadata-provider-ubuntunet.xml 
    #     dest=/opt/shibboleth-idp/conf

    - name: Copy Generic metadata providers
      copy: > 
        src=files/metadata-providers.xml 
        dest=/opt/shibboleth-idp/conf

    - name: Copy generic metadata file
      template: > 
        src=templates/idp_metadata.xml.j2
        dest=/opt/shibboleth-idp/metadata/idp_metadata.xml


    # 6.4. Relying party configuration
    # SWITCH recommends to keep the default IdP v3


    # 6.5. User authentication

    - name: Copy LDAP properties
      template: >
        src=templates/ldap.properties.j2
        dest=/opt/shibboleth-idp/conf

    - name: Add logger for LDAP authentication
      lineinfile: > 
        dest=/opt/shibboleth-idp/conf/logback.xml
        regexp="org.ldaptive.auth.Authenticator"
        insertbefore="Logs inbound and outbound protocols messages at DEBUG level"
        line='    <logger name="org.ldaptive.auth.Authenticator" level="INFO" />\n'

    # 6.6. Attribute resolution configuration

    # 6.7. Consent intercept configuration

    # 6.8. Enabling support for generating persistent IDs

    # 6.9. Configuring periodic encryption key rotation

    # 6.10. Login form customization

    # 6.11. IdP status URL configuration

    - name: Download IdP Status Page
      get_url: > 
        url=https://repo1.maven.org/maven2/jstl/jstl/1.2/jstl-1.2.jar
        dest=/opt/shibboleth-idp/edit-webapp/WEB-INF/lib/jstl-1.2.jar

    - name: Enable IdP status URL
      shell: "JAVACMD=/usr/bin/java /opt/shibboleth-idp/bin/build.sh -Didp.target.dir=/opt/shibboleth-idp"
      notify: restart tomcat

    - name: Allow access from host machine
      replace: >
        dest=/opt/shibboleth-idp/conf/access-control.xml
        regexp="{'127.0.0.1/32', '::1/128'}"
        replace="{'127.0.0.1/32', '::1/128', '192.168.33.0/24'}"
      notify: restart tomcat
      

    # 6.12. Hibernate ORM workaround for JPAStorageService

    - name: Create META-INF directory
      file: >
        path=/opt/shibboleth-idp/edit-webapp/WEB-INF/classes/META-INF
        state=directory

    - name: Copy ORM workaround
      copy: > 
        src=files/orm.xml 
        dest=/opt/shibboleth-idp/edit-webapp/WEB-INF/classes/META-INF

    - name: Rebuild id.war
      shell: "JAVACMD=/usr/bin/java /opt/shibboleth-idp/bin/build.sh -Didp.target.dir=/opt/shibboleth-idp"
      notify: restart tomcat


    # 6.13. Web application enablement

    - name: Enable IdP Web application
      copy: > 
        src=files/idp.xml 
        dest=/etc/tomcat7/Catalina/localhost/idp.xml
      notify: restart tomcat


  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

    - name: restart tomcat
      service: name=tomcat{{ tomcat_version }} state=restarted

    - name: restart postgres
      service: name=postgresql state=restarted

    # # TODO - Either create a dedicated service or use Tomcat
    # - name: restart shibboleth
    #   service: name=tomcat{{ tomcat_version }} state=restarted
